export default [{
  key: '1',
  shortname: '2018 Short Event',
  longname: '2018 LongName for an Event',
  venue: 'Somewhere in Australia',
  attendees: 100,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: true,
  unchecked: true,
  incomplete: true,
}, {
  key: '2',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '3',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '4',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '5',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '6',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '7',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '8',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '9',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}, {
  key: '10',
  shortname: 'Another Short Event',
  longname: 'Insert Very Long Event Name here',
  venue: 'Australia',
  attendees: 120,
  sponsors: 50,
  abstracts: 3,
  dates: 'July 2018 - August 2018', // Moment JS dates here
  active: false,
  unchecked: false,
  incomplete: false,
}];